#cloud-config
hostname: ${VM_NAME}
fqdn: ${VM_NAME}
disable_root: false
users:
  - name: ${USER}
    groups: users, admin, docker, sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: ${PASSWD}
    ssh_import_id:
      - gh:${GITHUB_USER}
  - name: ${VM_ADMIN}
    gecos: system acct
    groups: users, admin, docker, sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: ${PASSWD}
    ssh_authorized_keys:
      - ${VM_KEY}
package_update: ${UPDATE}
package_upgrade: ${UPGRADE}
packages:
  - wget
  - curl
  - git
  - build-essential
  - python3-pip
runcmd:
  - sudo -u ${VM_ADMIN} echo "export PATH=\"/home/${VM_ADMIN}/.local/bin:\$PATH\"" >> /home/${VM_ADMIN}/.profile 
  - git clone https://github.com/cloudymax/ansible-boilerplate.git
  - sudo -u ${VM_ADMIN} env "PATH=$PATH:/home/$VM_ADMIN/.local/bin" /ansible-boilerplate/provision.sh --ansible-user ${VM_ADMIN} --profile jax --cows random
