#cloud-config
cloud_config_modules:
 - apk_configure
 - apt_configure
 - apt_pipelining
 - bootcmd
 - seed_random
 - set_passwords
 - snap
 - [package_update_upgrade_install, always]
cloud_final_modules:
 - runcmd
 - rightscale_userdata
 - scripts-per-once
 - [scripts-per-boot, always]
 - scripts-per-instance
 - scripts-user
 - keys-to-console
 - phone-home
 - final-message
hostname: ${VM_NAME}
fqdn: ${VM_NAME}
disable_root: false
network:
  config: disabled
users:
  - name: ${USER}
    groups: users, admin, docker, sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: ${PASSWD}
    ssh_import_id:
      - gh:${GITHUB_USER}
  - name: ${VM_USER}
    gecos: system acct
    groups: users, admin, docker, sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: ${PASSWD}
    ssh_authorized_keys:
      - ${VM_KEY}
write_files:
- path: /etc/netplan/99-my-new-config.yaml
  permissions: '0644'
  content: |
    network:
      ethernets:
        enp0s3:
          dhcp4: no
          dhcp6: no
          addresses: [${IP_ADDRESS}/24]
          routes:
            - to: default
              via: ${GATEWAY}
          mtu: 1500
          nameservers:
            addresses: [$DNS]
      renderer: networkd
      version: 2
- path: /etc/unity-hub
  permissions: '0644'
  content: |
    #!/bin/bash
    xvfb-run -ae /dev/stdout /opt/unityhub/unityhub-bin --no-sandbox --headless "\$@"
snap:
  commands:
    00: ['install', '--beta', 'steam']
    01: ['install', 'firefox']
    # We have to use the snap version of firefox because the apt-version is not correctly 
    # detected as the system default which causes errors when unity-hub tries to authenticate
apt:
  primary:
    - arches: [default]
      uri: http://us.archive.ubuntu.com/ubuntu/
  sources:
    unityhub.list:
      source: deb https://hub.unity3d.com/linux/repos/deb stable main
package_update: true
package_upgrade: true
packages:
  - apt-utils
  - ca-certificates
  - libasound2
  - libc6-dev
  - libcap2
  - libgconf-2-4
  - libglu1
  - libgtk-3-0
  - libncurses5
  - libnotify4
  - libnss3
  - libxtst6
  - libxss1
  - cpio
  - lsb-release
  - python3-pip
  - docker.io
  - python-setuptools
  - xz-utils
  - atop
  - curl
  - git
  - git-lfs
  - jq
  - openssh-client
  - wget
  - software-properties-common  
  - zenity
  - libgbm1
  - gnupg
  - x11vnc
  - ubuntu-desktop
  - xvfb
  - ubuntu-drivers-common
bootcmd:
  - - echo "---Updating network config for use with static ip addressing---" && sleep 1
  - netplan --degug generate
  - netplan --debug apply
  - mkdir -p "/opt/unityhub/chrome-sandbox"
  - mkdir -p "/opt/unity/editors"
runcmd:
  - echo "---Installing Nvidia Drivers---" && sleep 1
  - ubuntu-drivers autoinstall
  - echo "---Downloading xorg.conf---" && sleep 1
  - curl https://raw.githubusercontent.com/cloudymax/Scrap-Metal/main/virtual-machines/qemu/configs/xorg.conf > /tmp/xorg.conf
  - cp /tmp/xorg.conf /etc/X11/xorg.conf 
  - echo "---installing older version of SSL as workaround for Unity Hub failing to launch---" && sleep 1
  - wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
  - sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
  - rm libssl1.1_1.1.1f-1ubuntu2_amd64.deb
  - echo "---Downloading Unity's Apt Key manually since its not in the Ubuntu keyserver---" && sleep 1
  - wget -qO- https://hub.unity3d.com/linux/keys/public | apt-key add -
  - echo "---Installing UnityHub---" && sleep 1
  - apt-get update -y
  - apt-get install -y unityhub
  - mv /etc/unity-hub /usr/bin/unity-hub
  - echo "--- Doanload and install Unity Editor version ${EDITOR_VERSION}---" && sleep 1
  - sudo xvfb-run -ae /dev/stdout /opt/unityhub/unityhub-bin --no-sandbox --headless install-path --set "/opt/unity/editors"
  - sudo xvfb-run -ae /dev/stdout /opt/unityhub/unityhub-bin --no-sandbox --headless install -v ${EDITOR_VERSION}
  - echo "---installing git lfs---" && Sleep 1
  - git lfs install --system --skip-repo
  - echo "---Setting SSH port and options---" && sleep 1
  - sed -i -e '/^Port/s/^.*$/Port 22/' /etc/ssh/sshd_config
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin yes/' /etc/ssh/sshd_config
  - sed -i -e '/^PasswordAuthentication/s/^.*$/PasswordAuthentication yes/' /etc/ssh/sshd_config
  - systemctl restart sshd
